name: pos_system_app
description: "Professional POS System App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  fl_chart: ^0.70.2

  # ðŸ”¥ FIREBASE CORE (REQUIRED)
  firebase_core: ^3.6.0

  # ðŸ” AUTHENTICATION (LOGIN)
  firebase_auth: ^5.3.1

  # â˜ï¸ DATABASE (STORE PRODUCTS, ORDERS, SALES)
  cloud_firestore: ^5.4.4

  # ðŸ“¦ STORAGE (PRODUCT IMAGES)
  firebase_storage: ^12.3.2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
